#pragma once

#define SKNGEXT_STRMSG TEXT("SDEE_SKNGEXT_MSG")

#define SKNGEXT_APPWND_TYPEMSG 1
#define SKNGEXT_DESKENV_TYPEMSG 2
#define SKNGEXT_SKNWND_TYPEMSG 3

#define SKNGEXT_APPWND_MSG_SKNREQUEST 1
#define SKNGEXT_APPWND_MSG_NEWSKNWND 2

#define SKNGEXT_SKNWND_MSG_UNLOAD 1
//#define SKNWNDEXT_MSG TEXT("SKNWNDEXT_MSG")
//#define SKNWNDEXT_WINDOWPOSCHANGED_PARAM 1
//#define SKNWNDEXT_PRM_CLOSE 2
//#define SKNWNDEXT_PRM_HIDE 3
//#define SKNWNDEXT_PRM_RESTORE 4

#define SKNGEXT_DESKENV_DESHMEMID TEXT("SKNG_SHMEMID")
#define SKNGEXT_DESKENV_RUN32EVENT TEXT("SKNGEXT_RUN32EVENT")
#define SKNGEXT_DESKENV_RUN32CMDLINE TEXT("SKNGEXT_RUN32CMDLINE" )